"""Curated journal catalog for the Journal Intelligence Engine.

Each entry carries indicative bibliometrics and submission requirements.
Sources: publisher web pages, Clarivate JCR summaries, Scopus CiteScore,
SCImago, and DOAJ as of the curation date. Values must be re-verified by
the user before submission. Entries are intentionally diverse across
medicine, surgery, wound care, nursing, public health, allied health,
biomedical science, oncology, pediatrics, and global health.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class JournalRecord:
    name: str
    issn: str | None
    eissn: str | None
    publisher: str
    specialty: str
    subspecialties: tuple[str, ...]
    keywords: tuple[str, ...]
    # Accepted study designs (uses our project StudyDesign vocabulary).
    accepted_designs: tuple[str, ...]
    # Accepted manuscript types (e.g. original, review, case_report).
    article_types: tuple[str, ...]
    # Indicative metrics (verify on publisher site).
    impact_factor: float | None
    citescore: float | None
    sjr: float | None
    h_index: int | None
    quartile: str | None
    acceptance_rate: float | None  # 0..1
    avg_review_weeks: int | None
    avg_publication_weeks: int | None
    # Open access / pricing.
    open_access: bool
    hybrid: bool
    apc_usd: int | None
    # Submission requirements.
    word_limit: int | None
    abstract_word_limit: int | None
    figure_limit: int | None
    table_limit: int | None
    reference_limit: int | None
    reference_style: str
    reporting_guidelines: tuple[str, ...]
    # Editorial.
    submission_url: str | None
    website: str | None = None
    indexed_in: tuple[str, ...] = field(default_factory=tuple)
    notes: str = ""


CATALOG: tuple[JournalRecord, ...] = (
    # ------------------------------------------------------------------ General medicine
    JournalRecord(
        name="The Lancet",
        issn="0140-6736", eissn="1474-547X",
        publisher="Elsevier",
        specialty="general_medicine",
        subspecialties=("clinical_trials", "global_health", "policy"),
        keywords=("clinical trial", "global health", "policy", "rct", "general medicine"),
        accepted_designs=("rct", "cohort", "systematic_review"),
        article_types=("original", "review", "comment"),
        impact_factor=98.4, citescore=104.0, sjr=14.2, h_index=799, quartile="Q1",
        acceptance_rate=0.05, avg_review_weeks=4, avg_publication_weeks=8,
        open_access=False, hybrid=True, apc_usd=6450,
        word_limit=4500, abstract_word_limit=300, figure_limit=8, table_limit=5,
        reference_limit=50, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "STARD"),
        submission_url="https://www.editorialmanager.com/thelancet/",
        website="https://www.thelancet.com/",
        indexed_in=("MEDLINE", "Scopus", "WoS"),
        notes="Extreme selectivity. Submissions require global health relevance.",
    ),
    JournalRecord(
        name="New England Journal of Medicine",
        issn="0028-4793", eissn="1533-4406",
        publisher="Massachusetts Medical Society",
        specialty="general_medicine",
        subspecialties=("clinical_trials", "internal_medicine"),
        keywords=("clinical trial", "internal medicine", "rct", "phase iii"),
        accepted_designs=("rct", "cohort"),
        article_types=("original", "review", "case_report"),
        impact_factor=158.5, citescore=107.0, sjr=22.4, h_index=1100, quartile="Q1",
        acceptance_rate=0.05, avg_review_weeks=4, avg_publication_weeks=10,
        open_access=False, hybrid=False, apc_usd=None,
        word_limit=2700, abstract_word_limit=250, figure_limit=5, table_limit=4,
        reference_limit=40, reference_style="nlm",
        reporting_guidelines=("CONSORT", "STROBE", "CARE"),
        submission_url="https://www.nejm.org/author-center",
        website="https://www.nejm.org/",
        indexed_in=("MEDLINE", "Scopus", "WoS"),
    ),
    JournalRecord(
        name="BMJ Open",
        issn=None, eissn="2044-6055",
        publisher="BMJ Publishing Group",
        specialty="general_medicine",
        subspecialties=("clinical_research", "public_health", "qualitative"),
        keywords=("open access", "general medicine", "qualitative", "public health"),
        accepted_designs=("rct", "cohort", "case_control", "cross_sectional", "qualitative", "mixed_methods", "quality_improvement"),
        article_types=("original", "protocol", "review"),
        impact_factor=2.4, citescore=4.5, sjr=1.1, h_index=148, quartile="Q1",
        acceptance_rate=0.5, avg_review_weeks=8, avg_publication_weeks=14,
        open_access=True, hybrid=False, apc_usd=2890,
        word_limit=5000, abstract_word_limit=300, figure_limit=8, table_limit=5,
        reference_limit=60, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "STARD", "COREQ", "SRQR", "SQUIRE"),
        submission_url="https://mc.manuscriptcentral.com/bmjopen",
        website="https://bmjopen.bmj.com/",
        indexed_in=("MEDLINE", "Scopus", "DOAJ"),
        notes="Broad scope; welcoming of protocols and negative results.",
    ),
    JournalRecord(
        name="JAMA Network Open",
        issn=None, eissn="2574-3805",
        publisher="American Medical Association",
        specialty="general_medicine",
        subspecialties=("clinical_research", "health_policy", "outcomes"),
        keywords=("outcomes", "clinical research", "epidemiology", "open access"),
        accepted_designs=("rct", "cohort", "case_control", "cross_sectional", "systematic_review", "secondary_analysis"),
        article_types=("original", "review", "research_letter"),
        impact_factor=10.5, citescore=14.0, sjr=4.1, h_index=160, quartile="Q1",
        acceptance_rate=0.16, avg_review_weeks=6, avg_publication_weeks=12,
        open_access=True, hybrid=False, apc_usd=3000,
        word_limit=3000, abstract_word_limit=350, figure_limit=5, table_limit=5,
        reference_limit=75, reference_style="ama",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "STARD"),
        submission_url="https://mc.manuscriptcentral.com/jamanetworkopen",
        website="https://jamanetwork.com/journals/jamanetworkopen",
        indexed_in=("MEDLINE", "Scopus"),
    ),
    JournalRecord(
        name="PLOS Medicine",
        issn=None, eissn="1549-1676",
        publisher="PLOS",
        specialty="general_medicine",
        subspecialties=("global_health", "public_health", "clinical_research"),
        keywords=("global health", "public health", "open access", "policy", "lmic"),
        accepted_designs=("rct", "cohort", "systematic_review", "qualitative"),
        article_types=("original", "review", "policy_forum"),
        impact_factor=15.8, citescore=22.0, sjr=6.0, h_index=270, quartile="Q1",
        acceptance_rate=0.08, avg_review_weeks=10, avg_publication_weeks=20,
        open_access=True, hybrid=False, apc_usd=5300,
        word_limit=6500, abstract_word_limit=300, figure_limit=8, table_limit=6,
        reference_limit=60, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "STARD", "SRQR"),
        submission_url="https://www.editorialmanager.com/pmedicine/",
        website="https://journals.plos.org/plosmedicine/",
        indexed_in=("MEDLINE", "Scopus", "DOAJ"),
    ),
    # ------------------------------------------------------------------ Surgery
    JournalRecord(
        name="Annals of Surgery",
        issn="0003-4932", eissn="1528-1140",
        publisher="Wolters Kluwer",
        specialty="surgery",
        subspecialties=("general_surgery", "surgical_oncology", "trauma"),
        keywords=("surgery", "surgical outcomes", "perioperative", "trauma", "oncology"),
        accepted_designs=("rct", "cohort", "systematic_review", "case_series"),
        article_types=("original", "review", "editorial"),
        impact_factor=10.1, citescore=17.0, sjr=4.0, h_index=290, quartile="Q1",
        acceptance_rate=0.15, avg_review_weeks=6, avg_publication_weeks=16,
        open_access=False, hybrid=True, apc_usd=4250,
        word_limit=4500, abstract_word_limit=300, figure_limit=8, table_limit=6,
        reference_limit=60, reference_style="ama",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "STARD", "SCARE", "PROCESS"),
        submission_url="https://journals.lww.com/annalsofsurgery/",
        website="https://journals.lww.com/annalsofsurgery/",
        indexed_in=("MEDLINE", "Scopus", "WoS"),
    ),
    JournalRecord(
        name="Plastic and Reconstructive Surgery",
        issn="0032-1052", eissn="1529-4242",
        publisher="Wolters Kluwer",
        specialty="surgery",
        subspecialties=("plastic_surgery", "reconstructive_surgery", "aesthetic", "microsurgery"),
        keywords=("plastic", "reconstructive", "aesthetic", "flap", "graft", "microsurgery", "craniofacial"),
        accepted_designs=("rct", "cohort", "case_series", "systematic_review"),
        article_types=("original", "review", "case_report"),
        impact_factor=5.2, citescore=7.4, sjr=1.7, h_index=180, quartile="Q1",
        acceptance_rate=0.20, avg_review_weeks=6, avg_publication_weeks=18,
        open_access=False, hybrid=True, apc_usd=3500,
        word_limit=3000, abstract_word_limit=200, figure_limit=8, table_limit=4,
        reference_limit=50, reference_style="ama",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "CARE", "SCARE"),
        submission_url="https://journals.lww.com/plasreconsurg/",
        website="https://journals.lww.com/plasreconsurg/",
        indexed_in=("MEDLINE", "Scopus"),
    ),
    JournalRecord(
        name="Burns",
        issn="0305-4179", eissn="1879-1409",
        publisher="Elsevier",
        specialty="surgery",
        subspecialties=("burn_surgery", "wound_care", "rehabilitation"),
        keywords=("burn", "scald", "scar", "rehabilitation", "burns rehabilitation"),
        accepted_designs=("rct", "cohort", "case_series", "qualitative"),
        article_types=("original", "review", "case_report"),
        impact_factor=3.2, citescore=4.8, sjr=0.8, h_index=110, quartile="Q1",
        acceptance_rate=0.30, avg_review_weeks=6, avg_publication_weeks=18,
        open_access=False, hybrid=True, apc_usd=3000,
        word_limit=4000, abstract_word_limit=250, figure_limit=6, table_limit=4,
        reference_limit=50, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "CARE", "SCARE"),
        submission_url="https://www.editorialmanager.com/jburn/",
        website="https://www.journals.elsevier.com/burns",
        indexed_in=("MEDLINE", "Scopus"),
    ),
    JournalRecord(
        name="Microsurgery",
        issn="0738-1085", eissn="1098-2752",
        publisher="Wiley",
        specialty="surgery",
        subspecialties=("microsurgery", "plastic_surgery", "reconstructive_surgery"),
        keywords=("microsurgery", "free flap", "microvascular", "anastomosis"),
        accepted_designs=("cohort", "case_series", "rct"),
        article_types=("original", "review", "case_report"),
        impact_factor=2.1, citescore=4.0, sjr=0.7, h_index=80, quartile="Q2",
        acceptance_rate=0.25, avg_review_weeks=8, avg_publication_weeks=20,
        open_access=False, hybrid=True, apc_usd=3500,
        word_limit=3500, abstract_word_limit=250, figure_limit=6, table_limit=4,
        reference_limit=40, reference_style="ama",
        reporting_guidelines=("CONSORT", "STROBE", "CARE", "SCARE"),
        submission_url="https://onlinelibrary.wiley.com/journal/10982752",
        website="https://onlinelibrary.wiley.com/journal/10982752",
        indexed_in=("MEDLINE", "Scopus"),
    ),
    JournalRecord(
        name="Aesthetic Plastic Surgery",
        issn="0364-216X", eissn="1432-5241",
        publisher="Springer",
        specialty="surgery",
        subspecialties=("aesthetic", "plastic_surgery"),
        keywords=("aesthetic", "cosmetic", "rhinoplasty", "breast augmentation", "facelift"),
        accepted_designs=("cohort", "case_series", "rct"),
        article_types=("original", "review", "case_report"),
        impact_factor=2.0, citescore=3.5, sjr=0.6, h_index=60, quartile="Q2",
        acceptance_rate=0.35, avg_review_weeks=6, avg_publication_weeks=16,
        open_access=False, hybrid=True, apc_usd=3200,
        word_limit=4000, abstract_word_limit=250, figure_limit=6, table_limit=4,
        reference_limit=40, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "CARE", "SCARE"),
        submission_url="https://www.editorialmanager.com/aeps/",
        website="https://link.springer.com/journal/266",
        indexed_in=("MEDLINE", "Scopus"),
    ),
    # ------------------------------------------------------------------ Wound care
    JournalRecord(
        name="Journal of Wound Care",
        issn="0969-0700", eissn="2052-2916",
        publisher="MA Healthcare",
        specialty="wound_care",
        subspecialties=("chronic_wounds", "diabetic_foot", "pressure_injury", "tissue_repair"),
        keywords=("wound", "ulcer", "dressing", "tissue", "healing", "debridement"),
        accepted_designs=("rct", "cohort", "case_series", "qualitative", "quality_improvement"),
        article_types=("original", "review", "case_report"),
        impact_factor=1.9, citescore=3.2, sjr=0.6, h_index=64, quartile="Q2",
        acceptance_rate=0.45, avg_review_weeks=6, avg_publication_weeks=12,
        open_access=False, hybrid=True, apc_usd=2400,
        word_limit=4000, abstract_word_limit=250, figure_limit=6, table_limit=4,
        reference_limit=40, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "CARE", "SQUIRE"),
        submission_url="https://www.magonlinelibrary.com/journal/jowc",
        website="https://www.magonlinelibrary.com/journal/jowc",
        indexed_in=("MEDLINE", "Scopus", "CINAHL"),
    ),
    JournalRecord(
        name="International Wound Journal",
        issn="1742-4801", eissn="1742-481X",
        publisher="Wiley",
        specialty="wound_care",
        subspecialties=("chronic_wounds", "diabetic_foot", "pressure_injury", "surgical_wounds"),
        keywords=("wound", "diabetic foot", "pressure injury", "chronic", "biofilm", "surgical wound"),
        accepted_designs=("rct", "cohort", "case_series", "systematic_review"),
        article_types=("original", "review", "case_report"),
        impact_factor=3.0, citescore=5.1, sjr=0.9, h_index=70, quartile="Q1",
        acceptance_rate=0.40, avg_review_weeks=6, avg_publication_weeks=14,
        open_access=True, hybrid=False, apc_usd=2750,
        word_limit=5000, abstract_word_limit=250, figure_limit=8, table_limit=5,
        reference_limit=60, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "CARE", "SCARE"),
        submission_url="https://mc.manuscriptcentral.com/iwj",
        website="https://onlinelibrary.wiley.com/journal/1742481x",
        indexed_in=("MEDLINE", "Scopus", "DOAJ"),
    ),
    JournalRecord(
        name="Wound Repair and Regeneration",
        issn="1067-1927", eissn="1524-475X",
        publisher="Wiley",
        specialty="wound_care",
        subspecialties=("tissue_repair", "biology", "translational"),
        keywords=("wound healing", "regeneration", "biology", "fibroblast", "growth factor"),
        accepted_designs=("rct", "cohort", "case_series", "preclinical"),
        article_types=("original", "review"),
        impact_factor=3.4, citescore=5.8, sjr=1.0, h_index=110, quartile="Q1",
        acceptance_rate=0.30, avg_review_weeks=8, avg_publication_weeks=18,
        open_access=False, hybrid=True, apc_usd=3450,
        word_limit=5000, abstract_word_limit=250, figure_limit=8, table_limit=5,
        reference_limit=60, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA"),
        submission_url="https://onlinelibrary.wiley.com/journal/1524475x",
        website="https://onlinelibrary.wiley.com/journal/1524475x",
        indexed_in=("MEDLINE", "Scopus"),
    ),
    JournalRecord(
        name="Diabetic Foot & Ankle",
        issn="2000-625X", eissn="2000-625X",
        publisher="Taylor & Francis",
        specialty="wound_care",
        subspecialties=("diabetic_foot", "endocrinology", "podiatry"),
        keywords=("diabetic foot", "ulcer", "amputation", "neuropathy", "charcot"),
        accepted_designs=("rct", "cohort", "case_series"),
        article_types=("original", "review", "case_report"),
        impact_factor=1.5, citescore=2.5, sjr=0.5, h_index=24, quartile="Q3",
        acceptance_rate=0.50, avg_review_weeks=6, avg_publication_weeks=12,
        open_access=True, hybrid=False, apc_usd=1850,
        word_limit=4000, abstract_word_limit=250, figure_limit=6, table_limit=4,
        reference_limit=40, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "CARE"),
        submission_url="https://www.tandfonline.com/loi/zdfa20",
        website="https://www.tandfonline.com/loi/zdfa20",
        indexed_in=("Scopus", "DOAJ"),
    ),
    # ------------------------------------------------------------------ Nursing
    JournalRecord(
        name="Journal of Advanced Nursing",
        issn="0309-2402", eissn="1365-2648",
        publisher="Wiley",
        specialty="nursing",
        subspecialties=("clinical_nursing", "nursing_education", "evidence_based_practice"),
        keywords=("nursing", "education", "competency", "patient safety", "evidence based"),
        accepted_designs=("rct", "cohort", "qualitative", "mixed_methods", "systematic_review", "quality_improvement"),
        article_types=("original", "review", "discursive"),
        impact_factor=3.5, citescore=6.8, sjr=1.4, h_index=178, quartile="Q1",
        acceptance_rate=0.18, avg_review_weeks=10, avg_publication_weeks=20,
        open_access=False, hybrid=True, apc_usd=3000,
        word_limit=7000, abstract_word_limit=300, figure_limit=6, table_limit=6,
        reference_limit=60, reference_style="apa7",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "COREQ", "SRQR", "SQUIRE"),
        submission_url="https://mc.manuscriptcentral.com/jan",
        website="https://onlinelibrary.wiley.com/journal/13652648",
        indexed_in=("MEDLINE", "CINAHL", "Scopus"),
    ),
    JournalRecord(
        name="International Journal of Nursing Studies",
        issn="0020-7489", eissn="1873-491X",
        publisher="Elsevier",
        specialty="nursing",
        subspecialties=("clinical_nursing", "evidence_based_practice", "policy"),
        keywords=("nursing", "systematic review", "intervention", "policy", "workforce"),
        accepted_designs=("rct", "cohort", "systematic_review", "qualitative", "mixed_methods"),
        article_types=("original", "review", "protocol"),
        impact_factor=8.1, citescore=12.0, sjr=2.4, h_index=160, quartile="Q1",
        acceptance_rate=0.12, avg_review_weeks=10, avg_publication_weeks=22,
        open_access=False, hybrid=True, apc_usd=3000,
        word_limit=6000, abstract_word_limit=300, figure_limit=6, table_limit=6,
        reference_limit=70, reference_style="apa7",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "COREQ", "SRQR"),
        submission_url="https://www.editorialmanager.com/ijns/",
        website="https://www.journals.elsevier.com/international-journal-of-nursing-studies",
        indexed_in=("MEDLINE", "CINAHL", "Scopus", "WoS"),
    ),
    JournalRecord(
        name="BMC Nursing",
        issn=None, eissn="1472-6955",
        publisher="Springer Nature",
        specialty="nursing",
        subspecialties=("clinical_nursing", "education", "global"),
        keywords=("nursing", "open access", "education", "low resource", "global"),
        accepted_designs=("rct", "cohort", "qualitative", "mixed_methods", "cross_sectional", "quality_improvement"),
        article_types=("original", "review", "protocol"),
        impact_factor=2.6, citescore=3.8, sjr=0.8, h_index=58, quartile="Q1",
        acceptance_rate=0.40, avg_review_weeks=8, avg_publication_weeks=14,
        open_access=True, hybrid=False, apc_usd=2390,
        word_limit=6000, abstract_word_limit=350, figure_limit=8, table_limit=6,
        reference_limit=60, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "COREQ", "SRQR", "SQUIRE"),
        submission_url="https://bmcnurs.biomedcentral.com/submission-guidelines",
        website="https://bmcnurs.biomedcentral.com/",
        indexed_in=("MEDLINE", "CINAHL", "Scopus", "DOAJ"),
    ),
    JournalRecord(
        name="Worldviews on Evidence-Based Nursing",
        issn="1545-102X", eissn="1741-6787",
        publisher="Wiley (Sigma)",
        specialty="nursing",
        subspecialties=("evidence_based_practice", "implementation", "synthesis"),
        keywords=("evidence based nursing", "implementation", "systematic review", "knowledge translation"),
        accepted_designs=("systematic_review", "rct", "cohort", "qualitative"),
        article_types=("original", "review", "implementation"),
        impact_factor=3.4, citescore=5.4, sjr=1.4, h_index=70, quartile="Q1",
        acceptance_rate=0.20, avg_review_weeks=8, avg_publication_weeks=18,
        open_access=False, hybrid=True, apc_usd=3000,
        word_limit=6000, abstract_word_limit=250, figure_limit=4, table_limit=4,
        reference_limit=60, reference_style="apa7",
        reporting_guidelines=("PRISMA", "CONSORT", "STROBE", "COREQ", "SRQR"),
        submission_url="https://mc.manuscriptcentral.com/wvn",
        website="https://sigmapubs.onlinelibrary.wiley.com/journal/17416787",
        indexed_in=("MEDLINE", "CINAHL", "Scopus"),
    ),
    JournalRecord(
        name="Nurse Education Today",
        issn="0260-6917", eissn="1532-2793",
        publisher="Elsevier",
        specialty="nursing",
        subspecialties=("nursing_education", "curriculum", "simulation"),
        keywords=("nursing education", "curriculum", "simulation", "preceptorship", "competence"),
        accepted_designs=("rct", "cohort", "qualitative", "mixed_methods", "cross_sectional"),
        article_types=("original", "review", "discursive"),
        impact_factor=3.9, citescore=7.0, sjr=1.4, h_index=120, quartile="Q1",
        acceptance_rate=0.20, avg_review_weeks=8, avg_publication_weeks=16,
        open_access=False, hybrid=True, apc_usd=3000,
        word_limit=5000, abstract_word_limit=250, figure_limit=4, table_limit=4,
        reference_limit=50, reference_style="apa7",
        reporting_guidelines=("STROBE", "COREQ", "SRQR", "SQUIRE"),
        submission_url="https://www.editorialmanager.com/ynedt/",
        website="https://www.journals.elsevier.com/nurse-education-today",
        indexed_in=("MEDLINE", "CINAHL", "Scopus"),
    ),
    # ------------------------------------------------------------------ Public health
    JournalRecord(
        name="BMC Public Health",
        issn=None, eissn="1471-2458",
        publisher="Springer Nature",
        specialty="public_health",
        subspecialties=("epidemiology", "global_health", "health_services"),
        keywords=("public health", "epidemiology", "surveillance", "global", "lmic", "behavioural"),
        accepted_designs=("cohort", "cross_sectional", "case_control", "qualitative", "mixed_methods", "quality_improvement"),
        article_types=("original", "review", "protocol"),
        impact_factor=4.0, citescore=5.1, sjr=1.3, h_index=170, quartile="Q1",
        acceptance_rate=0.30, avg_review_weeks=10, avg_publication_weeks=18,
        open_access=True, hybrid=False, apc_usd=2790,
        word_limit=6000, abstract_word_limit=350, figure_limit=10, table_limit=8,
        reference_limit=80, reference_style="vancouver",
        reporting_guidelines=("STROBE", "PRISMA", "COREQ", "SRQR", "CONSORT", "SQUIRE"),
        submission_url="https://bmcpublichealth.biomedcentral.com/submission-guidelines",
        website="https://bmcpublichealth.biomedcentral.com/",
        indexed_in=("MEDLINE", "Scopus", "DOAJ"),
    ),
    JournalRecord(
        name="The Lancet Global Health",
        issn=None, eissn="2214-109X",
        publisher="Elsevier",
        specialty="public_health",
        subspecialties=("global_health", "lmic", "infectious_disease"),
        keywords=("global health", "lmic", "low income", "infectious", "maternal"),
        accepted_designs=("rct", "cohort", "systematic_review", "cross_sectional"),
        article_types=("original", "review", "comment"),
        impact_factor=21.4, citescore=29.0, sjr=8.4, h_index=110, quartile="Q1",
        acceptance_rate=0.10, avg_review_weeks=6, avg_publication_weeks=14,
        open_access=True, hybrid=False, apc_usd=6500,
        word_limit=4500, abstract_word_limit=300, figure_limit=8, table_limit=5,
        reference_limit=50, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "STARD"),
        submission_url="https://www.thelancet.com/lancetgh",
        website="https://www.thelancet.com/journals/langlo/home",
        indexed_in=("MEDLINE", "Scopus"),
    ),
    JournalRecord(
        name="International Journal of Epidemiology",
        issn="0300-5771", eissn="1464-3685",
        publisher="Oxford University Press",
        specialty="public_health",
        subspecialties=("epidemiology", "methodology", "cohort_studies"),
        keywords=("epidemiology", "cohort", "case control", "methodology", "causal inference"),
        accepted_designs=("cohort", "case_control", "cross_sectional", "systematic_review"),
        article_types=("original", "review", "education"),
        impact_factor=7.7, citescore=12.0, sjr=2.9, h_index=240, quartile="Q1",
        acceptance_rate=0.15, avg_review_weeks=10, avg_publication_weeks=20,
        open_access=False, hybrid=True, apc_usd=4015,
        word_limit=4500, abstract_word_limit=300, figure_limit=6, table_limit=6,
        reference_limit=60, reference_style="vancouver",
        reporting_guidelines=("STROBE", "PRISMA"),
        submission_url="https://academic.oup.com/ije/pages/General_Instructions",
        website="https://academic.oup.com/ije",
        indexed_in=("MEDLINE", "Scopus", "WoS"),
    ),
    # ------------------------------------------------------------------ Oncology
    JournalRecord(
        name="JCO - Journal of Clinical Oncology",
        issn="0732-183X", eissn="1527-7755",
        publisher="ASCO",
        specialty="oncology",
        subspecialties=("clinical_oncology", "trials"),
        keywords=("oncology", "cancer", "chemotherapy", "rct", "phase iii", "survival"),
        accepted_designs=("rct", "cohort", "systematic_review"),
        article_types=("original", "review"),
        impact_factor=45.3, citescore=53.0, sjr=12.5, h_index=550, quartile="Q1",
        acceptance_rate=0.10, avg_review_weeks=6, avg_publication_weeks=14,
        open_access=False, hybrid=True, apc_usd=4500,
        word_limit=4000, abstract_word_limit=275, figure_limit=6, table_limit=6,
        reference_limit=50, reference_style="ama",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA"),
        submission_url="https://ascopubs.org/journal/jco",
        website="https://ascopubs.org/journal/jco",
        indexed_in=("MEDLINE", "Scopus", "WoS"),
    ),
    JournalRecord(
        name="BMC Cancer",
        issn=None, eissn="1471-2407",
        publisher="Springer Nature",
        specialty="oncology",
        subspecialties=("clinical_oncology", "translational", "epidemiology"),
        keywords=("cancer", "tumour", "oncology", "biomarker", "screening"),
        accepted_designs=("rct", "cohort", "case_control", "cross_sectional", "secondary_analysis"),
        article_types=("original", "review", "protocol"),
        impact_factor=3.4, citescore=4.4, sjr=1.0, h_index=140, quartile="Q2",
        acceptance_rate=0.45, avg_review_weeks=8, avg_publication_weeks=16,
        open_access=True, hybrid=False, apc_usd=2890,
        word_limit=5000, abstract_word_limit=350, figure_limit=8, table_limit=6,
        reference_limit=80, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "STARD"),
        submission_url="https://bmccancer.biomedcentral.com/submission-guidelines",
        website="https://bmccancer.biomedcentral.com/",
        indexed_in=("MEDLINE", "Scopus", "DOAJ"),
    ),
    # ------------------------------------------------------------------ Pediatrics
    JournalRecord(
        name="Pediatrics",
        issn="0031-4005", eissn="1098-4275",
        publisher="American Academy of Pediatrics",
        specialty="medicine",
        subspecialties=("pediatrics", "neonatology", "child_health"),
        keywords=("pediatrics", "children", "neonatal", "adolescent", "vaccine"),
        accepted_designs=("rct", "cohort", "case_control", "cross_sectional"),
        article_types=("original", "review", "case_report"),
        impact_factor=8.0, citescore=11.0, sjr=3.5, h_index=350, quartile="Q1",
        acceptance_rate=0.10, avg_review_weeks=8, avg_publication_weeks=18,
        open_access=False, hybrid=True, apc_usd=3500,
        word_limit=3000, abstract_word_limit=250, figure_limit=5, table_limit=4,
        reference_limit=40, reference_style="ama",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "CARE"),
        submission_url="https://publications.aap.org/pediatrics",
        website="https://publications.aap.org/pediatrics",
        indexed_in=("MEDLINE", "Scopus", "WoS"),
    ),
    # ------------------------------------------------------------------ Pharmacy / allied
    JournalRecord(
        name="Frontiers in Pharmacology",
        issn=None, eissn="1663-9812",
        publisher="Frontiers",
        specialty="allied_health",
        subspecialties=("pharmacy", "pharmacology", "translational"),
        keywords=("pharmacology", "drug", "pharmacokinetics", "clinical pharmacy"),
        accepted_designs=("rct", "cohort", "preclinical", "systematic_review"),
        article_types=("original", "review", "perspective"),
        impact_factor=4.4, citescore=7.0, sjr=1.2, h_index=140, quartile="Q1",
        acceptance_rate=0.50, avg_review_weeks=6, avg_publication_weeks=10,
        open_access=True, hybrid=False, apc_usd=2950,
        word_limit=12000, abstract_word_limit=350, figure_limit=15, table_limit=10,
        reference_limit=100, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA"),
        submission_url="https://www.frontiersin.org/journals/pharmacology",
        website="https://www.frontiersin.org/journals/pharmacology",
        indexed_in=("MEDLINE", "Scopus", "DOAJ"),
    ),
    JournalRecord(
        name="BMC Health Services Research",
        issn=None, eissn="1472-6963",
        publisher="Springer Nature",
        specialty="allied_health",
        subspecialties=("health_services", "policy", "quality"),
        keywords=("health services", "quality", "policy", "implementation", "workforce"),
        accepted_designs=("cohort", "qualitative", "mixed_methods", "quality_improvement", "cross_sectional"),
        article_types=("original", "review", "protocol"),
        impact_factor=2.7, citescore=4.0, sjr=1.0, h_index=130, quartile="Q1",
        acceptance_rate=0.40, avg_review_weeks=10, avg_publication_weeks=16,
        open_access=True, hybrid=False, apc_usd=2790,
        word_limit=6000, abstract_word_limit=350, figure_limit=8, table_limit=6,
        reference_limit=80, reference_style="vancouver",
        reporting_guidelines=("STROBE", "PRISMA", "COREQ", "SRQR", "SQUIRE", "CHEERS"),
        submission_url="https://bmchealthservres.biomedcentral.com/submission-guidelines",
        website="https://bmchealthservres.biomedcentral.com/",
        indexed_in=("MEDLINE", "Scopus", "DOAJ"),
    ),
    # ------------------------------------------------------------------ General open access / megajournal
    JournalRecord(
        name="PLOS ONE",
        issn=None, eissn="1932-6203",
        publisher="PLOS",
        specialty="biomedical_science",
        subspecialties=("multidisciplinary", "open_access"),
        keywords=("multidisciplinary", "open access", "rigour", "any methodology"),
        accepted_designs=("rct", "cohort", "case_control", "cross_sectional", "qualitative", "mixed_methods", "systematic_review", "case_series", "secondary_analysis"),
        article_types=("original", "review", "protocol"),
        impact_factor=3.2, citescore=5.8, sjr=0.9, h_index=420, quartile="Q1",
        acceptance_rate=0.45, avg_review_weeks=10, avg_publication_weeks=18,
        open_access=True, hybrid=False, apc_usd=2290,
        word_limit=None, abstract_word_limit=300, figure_limit=None, table_limit=None,
        reference_limit=None, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "STARD", "COREQ", "SRQR", "CARE", "SCARE", "SQUIRE", "CHEERS"),
        submission_url="https://journals.plos.org/plosone/s/submission-guidelines",
        website="https://journals.plos.org/plosone/",
        indexed_in=("MEDLINE", "Scopus", "DOAJ"),
        notes="Methodology-only review (no novelty bar).",
    ),
    JournalRecord(
        name="Scientific Reports",
        issn=None, eissn="2045-2322",
        publisher="Springer Nature",
        specialty="biomedical_science",
        subspecialties=("multidisciplinary", "open_access"),
        keywords=("multidisciplinary", "open access", "natural science", "biomedicine"),
        accepted_designs=("rct", "cohort", "case_control", "cross_sectional", "preclinical", "systematic_review"),
        article_types=("original",),
        impact_factor=3.8, citescore=7.5, sjr=1.0, h_index=290, quartile="Q1",
        acceptance_rate=0.45, avg_review_weeks=8, avg_publication_weeks=14,
        open_access=True, hybrid=False, apc_usd=2590,
        word_limit=None, abstract_word_limit=200, figure_limit=None, table_limit=None,
        reference_limit=None, reference_style="nature",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "STARD"),
        submission_url="https://www.nature.com/srep/author-instructions/submission-guidelines",
        website="https://www.nature.com/srep/",
        indexed_in=("MEDLINE", "Scopus", "DOAJ"),
    ),
    # ------------------------------------------------------------------ Dentistry
    JournalRecord(
        name="BMC Oral Health",
        issn=None, eissn="1472-6831",
        publisher="Springer Nature",
        specialty="dentistry",
        subspecialties=("oral_health", "periodontology", "public_dentistry"),
        keywords=("oral health", "dental caries", "periodontal", "dentistry", "orthodontics"),
        accepted_designs=("rct", "cohort", "case_control", "cross_sectional", "qualitative"),
        article_types=("original", "review", "case_report"),
        impact_factor=2.6, citescore=3.3, sjr=0.6, h_index=68, quartile="Q1",
        acceptance_rate=0.40, avg_review_weeks=8, avg_publication_weeks=14,
        open_access=True, hybrid=False, apc_usd=2390,
        word_limit=6000, abstract_word_limit=350, figure_limit=8, table_limit=6,
        reference_limit=80, reference_style="vancouver",
        reporting_guidelines=("CONSORT", "STROBE", "PRISMA", "CARE"),
        submission_url="https://bmcoralhealth.biomedcentral.com/submission-guidelines",
        website="https://bmcoralhealth.biomedcentral.com/",
        indexed_in=("MEDLINE", "Scopus", "DOAJ"),
    ),
)


def filter_catalog(
    *,
    specialty: str | None = None,
    open_access: bool | None = None,
    max_apc: int | None = None,
) -> list[JournalRecord]:
    out: list[JournalRecord] = []
    for j in CATALOG:
        if specialty and j.specialty != specialty and specialty not in j.subspecialties:
            continue
        if open_access is True and not j.open_access:
            continue
        if max_apc is not None and j.apc_usd is not None and j.apc_usd > max_apc:
            continue
        out.append(j)
    return out
