"""Curated funder catalog for GWIFOE.

Indicative metadata for international grant agencies, research councils,
philanthropies, government and industry funders. Values are conservative
public-facing summaries and must be re-verified at the funder's portal
before submission. No DOIs or unverifiable identifiers are stored.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class FunderRecord:
    name: str
    acronym: str | None
    funder_type: str  # international | research_council | philanthropy | government | industry | ngo
    country_focus: tuple[str, ...]  # ISO codes or "global"
    eligibility: tuple[str, ...]
    research_areas: tuple[str, ...]
    keywords: tuple[str, ...]
    career_stages: tuple[str, ...]  # student | early_career | mid_career | senior | institutional
    typical_award_min_usd: int | None
    typical_award_max_usd: int | None
    typical_duration_months: int | None
    success_rate: float | None  # 0..1
    review_weeks: int | None
    cycles_per_year: int | None
    next_deadline_hint: str | None  # plain-text e.g. "Rolling" or "Quarterly"
    requires_institution: bool
    requires_collaboration: bool
    open_to_lmic: bool
    apc_or_indirects_allowed: bool
    website: str | None
    portal: str | None
    proposal_format: tuple[str, ...]  # e.g. ("R01", "concept_note", "full_proposal")
    notes: str = ""
    tags: tuple[str, ...] = field(default_factory=tuple)


# Curated set spanning the user's listed agencies + a few high-relevance peers.
FUNDERS: tuple[FunderRecord, ...] = (
    FunderRecord(
        name="National Institutes of Health",
        acronym="NIH",
        funder_type="government",
        country_focus=("US", "global"),
        eligibility=("US institutions", "select foreign components"),
        research_areas=("medicine", "biomedical", "public_health", "clinical", "translational"),
        keywords=("nih", "r01", "r21", "k23", "biomedical", "clinical research", "translational"),
        career_stages=("early_career", "mid_career", "senior", "institutional"),
        typical_award_min_usd=50_000, typical_award_max_usd=2_500_000,
        typical_duration_months=60, success_rate=0.20, review_weeks=24, cycles_per_year=3,
        next_deadline_hint="Three standard cycles per year (Feb / Jun / Oct)",
        requires_institution=True, requires_collaboration=False, open_to_lmic=False,
        apc_or_indirects_allowed=True,
        website="https://www.nih.gov/", portal="https://grants.nih.gov/",
        proposal_format=("R01", "R21", "K23", "F31", "U01"),
        notes="Specific aims (1 page) precedes full proposal. Strict page limits per mechanism.",
        tags=("biomedical", "rigor", "specific_aims"),
    ),
    FunderRecord(
        name="United States Agency for International Development",
        acronym="USAID",
        funder_type="government",
        country_focus=("global", "lmic"),
        eligibility=("US-registered NGOs", "academic institutions", "international NGOs"),
        research_areas=("global_health", "public_health", "implementation", "health_systems"),
        keywords=("usaid", "global health", "implementation", "lmic", "health systems"),
        career_stages=("institutional",),
        typical_award_min_usd=250_000, typical_award_max_usd=25_000_000,
        typical_duration_months=60, success_rate=0.10, review_weeks=20, cycles_per_year=4,
        next_deadline_hint="Per BAA / NOFO postings",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://www.usaid.gov/", portal="https://www.grants.gov/",
        proposal_format=("concept_note", "full_proposal"),
        notes="Logical framework, M&E plan and theory of change are mandatory.",
        tags=("logframe", "moe", "implementation"),
    ),
    FunderRecord(
        name="Bill & Melinda Gates Foundation",
        acronym="Gates",
        funder_type="philanthropy",
        country_focus=("global", "lmic"),
        eligibility=("non-profits", "for-profits", "academic institutions"),
        research_areas=("global_health", "infectious_disease", "maternal_child_health", "vaccines", "innovation"),
        keywords=("gates", "global health", "vaccines", "tb", "hiv", "malaria", "maternal", "lmic"),
        career_stages=("early_career", "mid_career", "senior", "institutional"),
        typical_award_min_usd=100_000, typical_award_max_usd=10_000_000,
        typical_duration_months=36, success_rate=0.05, review_weeks=12, cycles_per_year=2,
        next_deadline_hint="Per Grand Challenges call",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://www.gatesfoundation.org/",
        portal="https://gcgh.grandchallenges.org/",
        proposal_format=("letter_of_inquiry", "full_proposal"),
        notes="Innovation and measurable impact are decisive criteria.",
        tags=("innovation", "impact", "lmic"),
    ),
    FunderRecord(
        name="Wellcome Trust",
        acronym="Wellcome",
        funder_type="philanthropy",
        country_focus=("UK", "global"),
        eligibility=("researchers worldwide", "host institutions"),
        research_areas=("biomedical", "global_health", "mental_health", "infectious_disease", "climate_health"),
        keywords=("wellcome", "discovery", "mental health", "climate health", "biomedical"),
        career_stages=("early_career", "mid_career", "senior"),
        typical_award_min_usd=100_000, typical_award_max_usd=4_000_000,
        typical_duration_months=60, success_rate=0.13, review_weeks=24, cycles_per_year=2,
        next_deadline_hint="Two rounds per year per scheme",
        requires_institution=True, requires_collaboration=False, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://wellcome.org/",
        portal="https://wellcome.org/grant-funding",
        proposal_format=("preliminary_application", "full_application"),
        notes="Discovery, Translation, and Climate & Health priorities.",
        tags=("discovery", "career"),
    ),
    FunderRecord(
        name="Horizon Europe",
        acronym="HE",
        funder_type="international",
        country_focus=("EU", "associated_countries", "global"),
        eligibility=("EU consortia", "associated country partners"),
        research_areas=("health", "innovation", "digital", "policy", "public_health"),
        keywords=("horizon europe", "consortium", "health cluster", "msca", "erc", "digital health"),
        career_stages=("early_career", "mid_career", "senior", "institutional"),
        typical_award_min_usd=1_000_000, typical_award_max_usd=15_000_000,
        typical_duration_months=48, success_rate=0.10, review_weeks=20, cycles_per_year=2,
        next_deadline_hint="Per work programme calls",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe_en",
        portal="https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/home",
        proposal_format=("part_a_admin", "part_b_technical"),
        notes="Cluster 1 (Health) and ERC are most relevant for medical research.",
        tags=("consortium", "open_science", "policy"),
    ),
    FunderRecord(
        name="UK Research and Innovation",
        acronym="UKRI",
        funder_type="research_council",
        country_focus=("UK",),
        eligibility=("UK institutions", "international co-investigators"),
        research_areas=("biomedical", "health", "social_sciences", "innovation"),
        keywords=("ukri", "mrc", "esrc", "epsrc", "uk", "innovation"),
        career_stages=("early_career", "mid_career", "senior", "institutional"),
        typical_award_min_usd=100_000, typical_award_max_usd=5_000_000,
        typical_duration_months=48, success_rate=0.20, review_weeks=20, cycles_per_year=3,
        next_deadline_hint="Rolling per council",
        requires_institution=True, requires_collaboration=False, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://www.ukri.org/", portal="https://funding-service.ukri.org/",
        proposal_format=("outline", "full_proposal"),
        notes="Pathways to impact and patient-public involvement (PPI) are required.",
        tags=("ppi", "impact_pathways"),
    ),
    FunderRecord(
        name="Medical Research Council",
        acronym="MRC",
        funder_type="research_council",
        country_focus=("UK", "global"),
        eligibility=("UK and partner institutions"),
        research_areas=("biomedical", "clinical", "translational", "global_health"),
        keywords=("mrc", "clinical trial", "translational", "biomedical", "uk"),
        career_stages=("early_career", "mid_career", "senior"),
        typical_award_min_usd=100_000, typical_award_max_usd=3_000_000,
        typical_duration_months=36, success_rate=0.18, review_weeks=20, cycles_per_year=3,
        next_deadline_hint="Quarterly",
        requires_institution=True, requires_collaboration=False, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://www.ukri.org/councils/mrc/",
        portal="https://funding-service.ukri.org/",
        proposal_format=("outline", "full_proposal"),
        notes="Strong methodology and statistical justification expected.",
        tags=("biomedical", "rigor"),
    ),
    FunderRecord(
        name="UNICEF",
        acronym="UNICEF",
        funder_type="international",
        country_focus=("global", "lmic"),
        eligibility=("governments", "NGOs", "academic institutions"),
        research_areas=("child_health", "maternal_health", "nutrition", "wash", "education"),
        keywords=("unicef", "child", "maternal", "nutrition", "wash", "lmic"),
        career_stages=("institutional",),
        typical_award_min_usd=50_000, typical_award_max_usd=5_000_000,
        typical_duration_months=24, success_rate=0.20, review_weeks=12, cycles_per_year=4,
        next_deadline_hint="Per country office calls",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=False,
        website="https://www.unicef.org/", portal="https://www.unicef.org/innovation/funds",
        proposal_format=("concept_note", "full_proposal"),
        notes="Country-office driven. Strong M&E and child rights framing required.",
        tags=("child_health", "moe"),
    ),
    FunderRecord(
        name="World Health Organization",
        acronym="WHO",
        funder_type="international",
        country_focus=("global",),
        eligibility=("governments", "WHO collaborating centres", "research consortia"),
        research_areas=("public_health", "infectious_disease", "ncd", "health_systems", "policy"),
        keywords=("who", "public health", "policy", "tdr", "vaccine", "global"),
        career_stages=("institutional",),
        typical_award_min_usd=10_000, typical_award_max_usd=2_000_000,
        typical_duration_months=24, success_rate=0.15, review_weeks=10, cycles_per_year=4,
        next_deadline_hint="Per call",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=False,
        website="https://www.who.int/", portal="https://www.who.int/about/funding",
        proposal_format=("concept_note", "full_proposal"),
        notes="TDR small grants well suited to LMIC researchers.",
        tags=("policy", "lmic"),
    ),
    FunderRecord(
        name="United Nations Development Programme",
        acronym="UNDP",
        funder_type="international",
        country_focus=("global", "lmic"),
        eligibility=("governments", "NGOs", "academic institutions"),
        research_areas=("health_systems", "sdgs", "policy", "development"),
        keywords=("undp", "sdg", "health systems", "policy", "lmic"),
        career_stages=("institutional",),
        typical_award_min_usd=25_000, typical_award_max_usd=3_000_000,
        typical_duration_months=24, success_rate=0.15, review_weeks=12, cycles_per_year=4,
        next_deadline_hint="Per call",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=False,
        website="https://www.undp.org/", portal="https://www.undp.org/funding",
        proposal_format=("concept_note", "full_proposal"),
        notes="SDG-aligned framing and country-office endorsement needed.",
        tags=("sdg", "policy"),
    ),
    FunderRecord(
        name="UNFPA",
        acronym="UNFPA",
        funder_type="international",
        country_focus=("global", "lmic"),
        eligibility=("governments", "NGOs", "research institutions"),
        research_areas=("reproductive_health", "maternal_health", "youth", "gender"),
        keywords=("unfpa", "reproductive health", "maternal", "gender", "youth"),
        career_stages=("institutional",),
        typical_award_min_usd=25_000, typical_award_max_usd=2_000_000,
        typical_duration_months=24, success_rate=0.18, review_weeks=10, cycles_per_year=3,
        next_deadline_hint="Per call",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=False,
        website="https://www.unfpa.org/", portal="https://www.unfpa.org/funding",
        proposal_format=("concept_note", "full_proposal"),
        notes="Adolescent and reproductive health priorities.",
        tags=("reproductive", "gender"),
    ),
    FunderRecord(
        name="World Bank",
        acronym="WB",
        funder_type="international",
        country_focus=("global", "lmic"),
        eligibility=("governments", "consortia"),
        research_areas=("health_systems", "economics", "policy", "development"),
        keywords=("world bank", "health financing", "economics", "policy", "lmic"),
        career_stages=("institutional",),
        typical_award_min_usd=100_000, typical_award_max_usd=20_000_000,
        typical_duration_months=48, success_rate=0.10, review_weeks=20, cycles_per_year=2,
        next_deadline_hint="Per call",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://www.worldbank.org/", portal="https://www.worldbank.org/en/programs/health",
        proposal_format=("concept_note", "full_proposal"),
        notes="Government-led; academic role usually as technical partner.",
        tags=("policy", "economics"),
    ),
    FunderRecord(
        name="African Development Bank",
        acronym="AfDB",
        funder_type="international",
        country_focus=("AFR", "lmic"),
        eligibility=("African governments", "regional institutions"),
        research_areas=("health_systems", "infrastructure", "human_capital", "policy"),
        keywords=("afdb", "africa", "health systems", "human capital"),
        career_stages=("institutional",),
        typical_award_min_usd=200_000, typical_award_max_usd=15_000_000,
        typical_duration_months=48, success_rate=0.12, review_weeks=20, cycles_per_year=2,
        next_deadline_hint="Per call",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://www.afdb.org/", portal="https://www.afdb.org/en/projects-and-operations",
        proposal_format=("concept_note", "full_proposal"),
        notes="Country ownership and co-financing important.",
        tags=("africa", "policy"),
    ),
    FunderRecord(
        name="Rockefeller Foundation",
        acronym="Rockefeller",
        funder_type="philanthropy",
        country_focus=("global", "lmic"),
        eligibility=("non-profits", "academic institutions"),
        research_areas=("public_health", "data_science", "climate_health", "food_systems"),
        keywords=("rockefeller", "data science", "climate", "food", "global"),
        career_stages=("mid_career", "senior", "institutional"),
        typical_award_min_usd=100_000, typical_award_max_usd=5_000_000,
        typical_duration_months=36, success_rate=0.10, review_weeks=12, cycles_per_year=2,
        next_deadline_hint="Per call",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://www.rockefellerfoundation.org/",
        portal="https://www.rockefellerfoundation.org/grants/",
        proposal_format=("letter_of_inquiry", "full_proposal"),
        notes="Innovation and equity framing weighted heavily.",
        tags=("innovation", "equity"),
    ),
    FunderRecord(
        name="Mastercard Foundation",
        acronym="MCF",
        funder_type="philanthropy",
        country_focus=("AFR", "lmic"),
        eligibility=("African universities", "NGOs"),
        research_areas=("youth_employment", "education", "health_workforce", "economic_inclusion"),
        keywords=("mastercard", "youth", "africa", "scholars", "workforce"),
        career_stages=("institutional",),
        typical_award_min_usd=250_000, typical_award_max_usd=20_000_000,
        typical_duration_months=60, success_rate=0.08, review_weeks=20, cycles_per_year=1,
        next_deadline_hint="Per programme",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://mastercardfdn.org/",
        portal="https://mastercardfdn.org/all/programs/",
        proposal_format=("concept_note", "full_proposal"),
        notes="Heavy programmatic - not project-by-project.",
        tags=("youth", "africa"),
    ),
    FunderRecord(
        name="Clinton Health Access Initiative",
        acronym="CHAI",
        funder_type="ngo",
        country_focus=("global", "lmic"),
        eligibility=("partner governments", "implementing partners"),
        research_areas=("hiv", "tb", "malaria", "ncd", "health_markets"),
        keywords=("chai", "hiv", "tb", "malaria", "ncd", "lmic", "access"),
        career_stages=("institutional",),
        typical_award_min_usd=100_000, typical_award_max_usd=5_000_000,
        typical_duration_months=36, success_rate=0.15, review_weeks=12, cycles_per_year=3,
        next_deadline_hint="Per programme",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=False,
        website="https://www.clintonhealthaccess.org/",
        portal="https://www.clintonhealthaccess.org/partner-with-us/",
        proposal_format=("concept_note", "full_proposal"),
        notes="Operates as implementing partner more than open grantmaker.",
        tags=("access", "implementation"),
    ),
    FunderRecord(
        name="Fogarty International Center",
        acronym="Fogarty",
        funder_type="government",
        country_focus=("global", "lmic"),
        eligibility=("US institutions partnered with LMIC"),
        research_areas=("global_health", "training", "ncd", "infectious_disease"),
        keywords=("fogarty", "lmic", "training", "global health", "d43", "k43"),
        career_stages=("early_career", "mid_career"),
        typical_award_min_usd=50_000, typical_award_max_usd=1_500_000,
        typical_duration_months=60, success_rate=0.20, review_weeks=24, cycles_per_year=1,
        next_deadline_hint="Annual",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://www.fic.nih.gov/", portal="https://grants.nih.gov/",
        proposal_format=("D43", "K43", "R21"),
        notes="Capacity building plus research; LMIC partnership mandatory.",
        tags=("capacity_building", "lmic"),
    ),
    FunderRecord(
        name="EDCTP3 (Global Health EDCTP3)",
        acronym="EDCTP3",
        funder_type="international",
        country_focus=("EU", "AFR", "lmic"),
        eligibility=("EU and Sub-Saharan African consortia"),
        research_areas=("infectious_disease", "clinical_trials", "vaccines", "diagnostics"),
        keywords=("edctp", "africa", "clinical trial", "vaccine", "infectious", "tb", "hiv"),
        career_stages=("mid_career", "senior", "institutional"),
        typical_award_min_usd=500_000, typical_award_max_usd=15_000_000,
        typical_duration_months=48, success_rate=0.12, review_weeks=24, cycles_per_year=2,
        next_deadline_hint="Per work programme",
        requires_institution=True, requires_collaboration=True, open_to_lmic=True,
        apc_or_indirects_allowed=True,
        website="https://www.global-health-edctp3.europa.eu/",
        portal="https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/home",
        proposal_format=("two_stage",),
        notes="EU-Africa partnership essential.",
        tags=("africa", "clinical_trial"),
    ),
)


def funders_by_acronym() -> dict[str, FunderRecord]:
    return {f.acronym or f.name: f for f in FUNDERS}
